name: E2E Pytest Selenium Allure
on:
  push:
    branches: ["main"]
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    env:
        ALLURE_RESULTS_DIR: allure-results
        TEST_EXECUTION_DIR: tests/integrador/test_integrador.py::test_integrador
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run E2E tests with Allure results
        run: |
          python -m pytest ${TEST_EXECUTION_DIR} -n 2 --alluredir=${ALLURE_RESULTS_DIR} --clean-alluredir
          
      - name: Upload Allure raw results   
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: allure-results
          path: allure-results/
          
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: logs
          path: logs/

      - name: Upload evidencias
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: evidencias
          path: artifacts/